[2024-12-23T08:37:38.096+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-23T08:37:38.141+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: streaming_pipeline.cdc_spark_streaming_to_datalake manual__2024-12-23T08:37:34.113449+00:00 [queued]>
[2024-12-23T08:37:38.158+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: streaming_pipeline.cdc_spark_streaming_to_datalake manual__2024-12-23T08:37:34.113449+00:00 [queued]>
[2024-12-23T08:37:38.158+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-23T08:37:38.176+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): cdc_spark_streaming_to_datalake> on 2024-12-23 08:37:34.113449+00:00
[2024-12-23T08:37:38.188+0000] {standard_task_runner.py:63} INFO - Started process 740 to run task
[2024-12-23T08:37:38.192+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'streaming_pipeline', 'cdc_spark_streaming_to_datalake', 'manual__2024-12-23T08:37:34.113449+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/pipline_stream.py', '--cfg-path', '/tmp/tmpkouv4ir5']
[2024-12-23T08:37:38.198+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask cdc_spark_streaming_to_datalake
[2024-12-23T08:37:38.270+0000] {task_command.py:426} INFO - Running <TaskInstance: streaming_pipeline.cdc_spark_streaming_to_datalake manual__2024-12-23T08:37:34.113449+00:00 [running]> on host 0b4a5bf62610
[2024-12-23T08:37:38.386+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='streaming_pipeline' AIRFLOW_CTX_TASK_ID='cdc_spark_streaming_to_datalake' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T08:37:34.113449+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T08:37:34.113449+00:00'
[2024-12-23T08:37:38.388+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-23T08:37:38.410+0000] {logging_mixin.py:188} INFO - Checking JAR files...:  True
[2024-12-23T08:52:30.496+0000] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-12-23T08:52:30.498+0000] {logging_mixin.py:188} WARNING -   File "/opt/***/dags/stream_processing/spark_streaming_to_dl.py", line 121, in create_spark_session
    ).getOrCreate()
      ^^^^^^^^^^^^^
[2024-12-23T08:52:30.499+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-23T08:52:30.500+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
[2024-12-23T08:52:30.500+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2024-12-23T08:52:30.501+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
[2024-12-23T08:52:30.501+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
[2024-12-23T08:52:30.502+0000] {logging_mixin.py:188} WARNING - pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-12-23T08:52:30.503+0000] {spark_streaming_to_dl.py:127} ERROR - Couldn't create the spark session due to exception: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-12-23T08:52:30.504+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-23T08:52:30.505+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stream_processing/spark_streaming_to_dl.py", line 259, in run_all
    load_minio_config(
        ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sparkContext'
[2024-12-23T08:52:30.519+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=streaming_pipeline, task_id=cdc_spark_streaming_to_datalake, run_id=manual__2024-12-23T08:37:34.113449+00:00, execution_date=20241223T083734, start_date=20241223T083738, end_date=20241223T085230
[2024-12-23T08:52:30.541+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 60 for task cdc_spark_streaming_to_datalake ('NoneType' object has no attribute 'sparkContext'; 740)
[2024-12-23T08:52:30.575+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-23T08:52:30.595+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T08:52:30.598+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
