[2024-12-23T18:30:15.375+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-23T18:30:15.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: streaming_pipeline.simulation_data_with_image_speech manual__2024-12-23T18:30:10.984310+00:00 [queued]>
[2024-12-23T18:30:15.447+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: streaming_pipeline.simulation_data_with_image_speech manual__2024-12-23T18:30:10.984310+00:00 [queued]>
[2024-12-23T18:30:15.448+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-23T18:30:15.475+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): simulation_data_with_image_speech> on 2024-12-23 18:30:10.984310+00:00
[2024-12-23T18:30:15.487+0000] {standard_task_runner.py:63} INFO - Started process 1489 to run task
[2024-12-23T18:30:15.490+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'streaming_pipeline', 'simulation_data_with_image_speech', 'manual__2024-12-23T18:30:10.984310+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_stream.py', '--cfg-path', '/tmp/tmpgkx6x5tj']
[2024-12-23T18:30:15.493+0000] {standard_task_runner.py:91} INFO - Job 155: Subtask simulation_data_with_image_speech
[2024-12-23T18:30:15.576+0000] {task_command.py:426} INFO - Running <TaskInstance: streaming_pipeline.simulation_data_with_image_speech manual__2024-12-23T18:30:10.984310+00:00 [running]> on host 0b4a5bf62610
[2024-12-23T18:30:15.722+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='streaming_pipeline' AIRFLOW_CTX_TASK_ID='simulation_data_with_image_speech' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T18:30:10.984310+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T18:30:10.984310+00:00'
[2024-12-23T18:30:15.724+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-23T18:30:15.983+0000] {logging_mixin.py:188} INFO - Not exists table: green_trip_raw_2024_04_03
[2024-12-23T18:30:16.011+0000] {logging_mixin.py:188} INFO - Created table: green_trip_raw_2024_04_03
[2024-12-23T18:30:16.015+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.4', 29092)]>: connecting to broker:29092 [('172.19.0.4', 29092) IPv4]
[2024-12-23T18:30:16.017+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-12-23T18:30:16.025+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.4', 29092)]>: Connection complete.
[2024-12-23T18:30:16.132+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-12-23T18:30:16.133+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-12-23T18:30:16.139+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.4', 29092)]>: connecting to broker:29092 [('172.19.0.4', 29092) IPv4]
[2024-12-23T18:30:16.143+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-12-23T18:30:16.146+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.4', 29092)]>: Connection complete.
[2024-12-23T18:30:16.252+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-12-23T18:30:16.252+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-12-23T18:30:16.253+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-12-23T18:30:16.358+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-12-23T18:30:16.360+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-12-23T18:30:16.370+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.19.0.4', 29092)]>: connecting to broker:29092 [('172.19.0.4', 29092) IPv4]
[2024-12-23T18:30:16.372+0000] {conn.py:957} INFO - Probing node 1 broker version
[2024-12-23T18:30:16.373+0000] {conn.py:393} INFO - <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.19.0.4', 29092)]>: Connection complete.
[2024-12-23T18:30:16.374+0000] {conn.py:673} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.19.0.4', 29092)]>: Closing connection. 
[2024-12-23T18:30:16.480+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-12-23T18:30:16.481+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-12-23T18:30:16.482+0000] {logging_mixin.py:188} INFO - Connected to Kafka
[2024-12-23T18:30:16.482+0000] {insert_data_to_db.py:136} INFO - Topic raw_image_2024_04_03 already exists. Skipping creation!
[2024-12-23T18:30:16.483+0000] {insert_data_to_db.py:136} INFO - Topic raw_speech_2024_04_03 already exists. Skipping creation!
[2024-12-23T18:30:16.496+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003834. Error: name 'args' is not defined
[2024-12-23T18:30:16.516+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003834. Error: name 'args' is not defined
[2024-12-23T18:30:16.517+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-0 to green_trip_raw_2024_04_03
[2024-12-23T18:30:16.518+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:17.520+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:18.542+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003855. Error: name 'args' is not defined
[2024-12-23T18:30:18.569+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003855. Error: name 'args' is not defined
[2024-12-23T18:30:18.571+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-1 to green_trip_raw_2024_04_03
[2024-12-23T18:30:18.572+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:19.574+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:20.584+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003856. Error: name 'args' is not defined
[2024-12-23T18:30:20.603+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003856. Error: name 'args' is not defined
[2024-12-23T18:30:20.604+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-2 to green_trip_raw_2024_04_03
[2024-12-23T18:30:20.605+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:21.606+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:22.617+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003857. Error: name 'args' is not defined
[2024-12-23T18:30:22.638+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003857. Error: name 'args' is not defined
[2024-12-23T18:30:22.639+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-3 to green_trip_raw_2024_04_03
[2024-12-23T18:30:22.640+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:23.641+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:24.653+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003861. Error: name 'args' is not defined
[2024-12-23T18:30:24.674+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003861. Error: name 'args' is not defined
[2024-12-23T18:30:24.676+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-4 to green_trip_raw_2024_04_03
[2024-12-23T18:30:24.677+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:25.678+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:26.689+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003862. Error: name 'args' is not defined
[2024-12-23T18:30:26.708+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003862. Error: name 'args' is not defined
[2024-12-23T18:30:26.709+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-5 to green_trip_raw_2024_04_03
[2024-12-23T18:30:26.710+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:27.712+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:28.723+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003863. Error: name 'args' is not defined
[2024-12-23T18:30:28.740+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003863. Error: name 'args' is not defined
[2024-12-23T18:30:28.741+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-6 to green_trip_raw_2024_04_03
[2024-12-23T18:30:28.742+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:29.743+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:30.754+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003864. Error: name 'args' is not defined
[2024-12-23T18:30:30.777+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003864. Error: name 'args' is not defined
[2024-12-23T18:30:30.779+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-7 to green_trip_raw_2024_04_03
[2024-12-23T18:30:30.780+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:31.781+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:32.791+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003866. Error: name 'args' is not defined
[2024-12-23T18:30:32.810+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003866. Error: name 'args' is not defined
[2024-12-23T18:30:32.811+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-8 to green_trip_raw_2024_04_03
[2024-12-23T18:30:32.812+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:33.813+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:34.823+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003867. Error: name 'args' is not defined
[2024-12-23T18:30:34.840+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003867. Error: name 'args' is not defined
[2024-12-23T18:30:34.842+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-9 to green_trip_raw_2024_04_03
[2024-12-23T18:30:34.843+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:35.843+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:36.854+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003868. Error: name 'args' is not defined
[2024-12-23T18:30:36.872+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003868. Error: name 'args' is not defined
[2024-12-23T18:30:36.873+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-10 to green_trip_raw_2024_04_03
[2024-12-23T18:30:36.874+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:37.875+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:38.885+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003870. Error: name 'args' is not defined
[2024-12-23T18:30:38.902+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003870. Error: name 'args' is not defined
[2024-12-23T18:30:38.904+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-11 to green_trip_raw_2024_04_03
[2024-12-23T18:30:38.905+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:39.906+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:40.917+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003871. Error: name 'args' is not defined
[2024-12-23T18:30:40.935+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003871. Error: name 'args' is not defined
[2024-12-23T18:30:40.936+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-12 to green_trip_raw_2024_04_03
[2024-12-23T18:30:40.937+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:41.938+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:42.951+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003872. Error: name 'args' is not defined
[2024-12-23T18:30:42.975+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003872. Error: name 'args' is not defined
[2024-12-23T18:30:42.977+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-13 to green_trip_raw_2024_04_03
[2024-12-23T18:30:42.977+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:43.977+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:44.994+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003873. Error: name 'args' is not defined
[2024-12-23T18:30:45.024+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003873. Error: name 'args' is not defined
[2024-12-23T18:30:45.026+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-14 to green_trip_raw_2024_04_03
[2024-12-23T18:30:45.027+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:46.031+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:47.043+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003874. Error: name 'args' is not defined
[2024-12-23T18:30:47.086+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003874. Error: name 'args' is not defined
[2024-12-23T18:30:47.089+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-15 to green_trip_raw_2024_04_03
[2024-12-23T18:30:47.090+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:48.092+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:49.108+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003875. Error: name 'args' is not defined
[2024-12-23T18:30:49.140+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003875. Error: name 'args' is not defined
[2024-12-23T18:30:49.142+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-16 to green_trip_raw_2024_04_03
[2024-12-23T18:30:49.144+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:50.145+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:51.161+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003876. Error: name 'args' is not defined
[2024-12-23T18:30:51.184+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003876. Error: name 'args' is not defined
[2024-12-23T18:30:51.185+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-17 to green_trip_raw_2024_04_03
[2024-12-23T18:30:51.187+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:52.188+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:53.210+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003877. Error: name 'args' is not defined
[2024-12-23T18:30:53.259+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003877. Error: name 'args' is not defined
[2024-12-23T18:30:53.266+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-18 to green_trip_raw_2024_04_03
[2024-12-23T18:30:53.267+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:54.268+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:55.308+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003878. Error: name 'args' is not defined
[2024-12-23T18:30:55.412+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003878. Error: name 'args' is not defined
[2024-12-23T18:30:55.414+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-19 to green_trip_raw_2024_04_03
[2024-12-23T18:30:55.433+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:56.435+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:57.449+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003879. Error: name 'args' is not defined
[2024-12-23T18:30:57.487+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003879. Error: name 'args' is not defined
[2024-12-23T18:30:57.497+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-20 to green_trip_raw_2024_04_03
[2024-12-23T18:30:57.501+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:30:58.515+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:30:59.533+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400003880. Error: name 'args' is not defined
[2024-12-23T18:30:59.604+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400003880. Error: name 'args' is not defined
[2024-12-23T18:30:59.607+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-21 to green_trip_raw_2024_04_03
[2024-12-23T18:30:59.609+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:31:00.610+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:31:01.087+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-12-23T18:31:01.092+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-12-23T18:31:01.099+0000] {process_utils.py:132} INFO - Sending 15 to group 1489. PIDs of all processes in the group: [1489]
[2024-12-23T18:31:01.101+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1489
[2024-12-23T18:31:01.104+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-23T18:31:01.106+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-23T18:31:01.145+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stream_processing/insert_data_to_db.py", line 293, in simulate_data_with_image
    countdown_sleep(args.time_sleep)
  File "/opt/airflow/dags/stream_processing/insert_data_to_db.py", line 57, in countdown_sleep
    time.sleep(1)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-23T18:31:01.190+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=streaming_pipeline, task_id=simulation_data_with_image_speech, run_id=manual__2024-12-23T18:30:10.984310+00:00, execution_date=20241223T183010, start_date=20241223T183015, end_date=20241223T183101
[2024-12-23T18:31:01.228+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 155 for task simulation_data_with_image_speech ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(streaming_pipeline, simulation_data_with_image_speech, manual__2024-12-23T18:30:10.984310+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'simulation_data_with_image_speech', 'dag_id': 'streaming_pipeline', 'run_id': 'manual__2024-12-23T18:30:10.984310+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 12, 23, 18, 30, 15, 432175, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 12, 23, 18, 31, 1, 188336, tzinfo=Timezone('UTC')), 'duration': 45}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 1489)
[2024-12-23T18:31:01.307+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1489, status='terminated', exitcode=1, started='18:30:15') (1489) terminated with exit code 1
