[2024-12-23T07:42:40.464+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-23T07:42:40.504+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: streaming_pipeline.simulation_data_with_image_speech manual__2024-12-23T07:18:15.038951+00:00 [queued]>
[2024-12-23T07:42:40.521+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: streaming_pipeline.simulation_data_with_image_speech manual__2024-12-23T07:18:15.038951+00:00 [queued]>
[2024-12-23T07:42:40.522+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-23T07:42:40.544+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): simulation_data_with_image_speech> on 2024-12-23 07:18:15.038951+00:00
[2024-12-23T07:42:40.551+0000] {standard_task_runner.py:63} INFO - Started process 963 to run task
[2024-12-23T07:42:40.553+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'streaming_pipeline', 'simulation_data_with_image_speech', 'manual__2024-12-23T07:18:15.038951+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/pipline_stream.py', '--cfg-path', '/tmp/tmpjw__kd8i']
[2024-12-23T07:42:40.556+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask simulation_data_with_image_speech
[2024-12-23T07:42:40.613+0000] {task_command.py:426} INFO - Running <TaskInstance: streaming_pipeline.simulation_data_with_image_speech manual__2024-12-23T07:18:15.038951+00:00 [running]> on host 45ad5a543c58
[2024-12-23T07:42:40.703+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='streaming_pipeline' AIRFLOW_CTX_TASK_ID='simulation_data_with_image_speech' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T07:18:15.038951+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T07:18:15.038951+00:00'
[2024-12-23T07:42:40.705+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-23T07:42:40.717+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-23T07:42:40.718+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 233, in execute
    self.op_kwargs = self.determine_kwargs(context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 244, in determine_kwargs
    return KeywordParameters.determine(self.python_callable, self.op_args, context).unpacking()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 163, in determine
    raise ValueError(f"The key {name!r} in args is a part of kwargs and therefore reserved.")
ValueError: The key 'conn' in args is a part of kwargs and therefore reserved.
[2024-12-23T07:42:40.730+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=streaming_pipeline, task_id=simulation_data_with_image_speech, run_id=manual__2024-12-23T07:18:15.038951+00:00, execution_date=20241223T071815, start_date=20241223T074240, end_date=20241223T074240
[2024-12-23T07:42:40.745+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 35 for task simulation_data_with_image_speech (The key 'conn' in args is a part of kwargs and therefore reserved.; 963)
[2024-12-23T07:42:40.767+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-23T07:42:40.781+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
