[2024-12-23T08:34:26.976+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-23T08:34:27.030+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: streaming_pipeline.cdc_spark_streaming_to_datalake manual__2024-12-23T08:34:25.209463+00:00 [queued]>
[2024-12-23T08:34:27.044+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: streaming_pipeline.cdc_spark_streaming_to_datalake manual__2024-12-23T08:34:25.209463+00:00 [queued]>
[2024-12-23T08:34:27.044+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-23T08:34:27.063+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): cdc_spark_streaming_to_datalake> on 2024-12-23 08:34:25.209463+00:00
[2024-12-23T08:34:27.073+0000] {standard_task_runner.py:63} INFO - Started process 563 to run task
[2024-12-23T08:34:27.078+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'streaming_pipeline', 'cdc_spark_streaming_to_datalake', 'manual__2024-12-23T08:34:25.209463+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/pipline_stream.py', '--cfg-path', '/tmp/tmpmkvptisz']
[2024-12-23T08:34:27.082+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask cdc_spark_streaming_to_datalake
[2024-12-23T08:34:27.184+0000] {task_command.py:426} INFO - Running <TaskInstance: streaming_pipeline.cdc_spark_streaming_to_datalake manual__2024-12-23T08:34:25.209463+00:00 [running]> on host 0b4a5bf62610
[2024-12-23T08:34:27.405+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='streaming_pipeline' AIRFLOW_CTX_TASK_ID='cdc_spark_streaming_to_datalake' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T08:34:25.209463+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T08:34:25.209463+00:00'
[2024-12-23T08:34:27.407+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-23T08:34:27.439+0000] {spark_streaming_to_dl.py:55} ERROR - JAR file E:/BigData_2/MyProject/jars/hadoop-aws-3.3.4.jar does not exist!
[2024-12-23T08:34:27.440+0000] {logging_mixin.py:188} INFO - Checking JAR files...:  False
[2024-12-23T08:40:44.996+0000] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-12-23T08:40:44.998+0000] {logging_mixin.py:188} WARNING -   File "/opt/***/dags/stream_processing/spark_streaming_to_dl.py", line 121, in create_spark_session
    ).getOrCreate()
      ^^^^^^^^^^^^^
[2024-12-23T08:40:44.999+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-23T08:40:45.000+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
[2024-12-23T08:40:45.000+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2024-12-23T08:40:45.001+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
[2024-12-23T08:40:45.002+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
[2024-12-23T08:40:45.003+0000] {logging_mixin.py:188} WARNING - pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-12-23T08:40:45.004+0000] {spark_streaming_to_dl.py:127} ERROR - Couldn't create the spark session due to exception: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-12-23T08:40:45.005+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-23T08:40:45.007+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stream_processing/spark_streaming_to_dl.py", line 259, in run_all
    spark.sparkContext,
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sparkContext'
[2024-12-23T08:40:45.021+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=streaming_pipeline, task_id=cdc_spark_streaming_to_datalake, run_id=manual__2024-12-23T08:34:25.209463+00:00, execution_date=20241223T083425, start_date=20241223T083427, end_date=20241223T084045
[2024-12-23T08:40:45.042+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task cdc_spark_streaming_to_datalake ('NoneType' object has no attribute 'sparkContext'; 563)
[2024-12-23T08:40:45.096+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-23T08:40:45.113+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T08:40:45.116+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
