[2024-12-22T18:24:20.519+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:24:20.521+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:24:20.525+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:24:20.524+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:24:20.593+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:24:20.588+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:24:20.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:24:20.623+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.110 seconds
[2024-12-22T18:24:51.049+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:24:51.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:24:51.060+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:24:51.058+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:24:51.125+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:24:51.112+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:24:51.127+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:24:51.207+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.197 seconds
[2024-12-22T18:25:21.915+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:25:21.917+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:25:21.920+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:25:21.919+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:25:21.975+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:25:21.967+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:25:21.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:25:22.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.128 seconds
[2024-12-22T18:25:52.580+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:25:52.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:25:52.584+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:25:52.583+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:25:52.614+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:25:52.609+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:25:52.616+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:25:52.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.065 seconds
[2024-12-22T18:26:23.095+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:26:23.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:26:23.098+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:26:23.098+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:26:23.128+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:26:23.123+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:26:23.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:26:23.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.066 seconds
[2024-12-22T18:26:53.597+0000] {processor.py:161} INFO - Started process (PID=354) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:26:53.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:26:53.601+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:26:53.600+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:26:53.633+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:26:53.628+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:26:53.635+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:26:53.659+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.067 seconds
[2024-12-22T18:27:23.980+0000] {processor.py:161} INFO - Started process (PID=419) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:27:23.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:27:23.984+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:27:23.983+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:27:24.014+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:27:24.009+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:27:24.015+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:27:24.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.063 seconds
[2024-12-22T18:27:54.123+0000] {processor.py:161} INFO - Started process (PID=478) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:27:54.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:27:54.126+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:27:54.126+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:27:54.156+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:27:54.150+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:27:54.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:27:54.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.064 seconds
[2024-12-22T18:28:09.098+0000] {processor.py:161} INFO - Started process (PID=531) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:28:09.100+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:28:09.103+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:28:09.103+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:28:09.168+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:28:09.159+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:28:09.171+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:28:09.208+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.118 seconds
[2024-12-22T18:28:39.317+0000] {processor.py:161} INFO - Started process (PID=590) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:28:39.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:28:39.320+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:28:39.319+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:28:39.350+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:28:39.345+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:28:39.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:28:39.373+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.061 seconds
[2024-12-22T18:29:09.658+0000] {processor.py:161} INFO - Started process (PID=649) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:29:09.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:29:09.662+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:29:09.661+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:29:09.695+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:29:09.689+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:29:09.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:29:09.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.067 seconds
[2024-12-22T18:29:40.572+0000] {processor.py:161} INFO - Started process (PID=706) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:29:40.574+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:29:40.576+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:29:40.576+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:29:40.607+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:29:40.601+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:29:40.609+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:29:40.634+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.067 seconds
[2024-12-22T18:30:11.026+0000] {processor.py:161} INFO - Started process (PID=765) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:30:11.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:30:11.029+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:30:11.029+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:30:11.062+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:30:11.056+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:30:11.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:30:11.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.067 seconds
[2024-12-22T18:30:41.307+0000] {processor.py:161} INFO - Started process (PID=824) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:30:41.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:30:41.310+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:30:41.309+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:30:41.342+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:30:41.335+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:30:41.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:30:41.367+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.065 seconds
[2024-12-22T18:31:11.811+0000] {processor.py:161} INFO - Started process (PID=883) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:31:11.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:31:11.814+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:31:11.814+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:31:11.841+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:31:11.836+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:31:11.843+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:31:11.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.058 seconds
[2024-12-22T18:31:42.410+0000] {processor.py:161} INFO - Started process (PID=942) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:31:42.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:31:42.413+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:31:42.413+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:31:42.444+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:31:42.439+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:31:42.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:31:42.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.063 seconds
[2024-12-22T18:32:12.702+0000] {processor.py:161} INFO - Started process (PID=1001) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:32:12.704+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:32:12.707+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:32:12.706+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:32:12.737+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:32:12.733+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:32:12.740+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:32:12.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.066 seconds
[2024-12-22T18:32:43.242+0000] {processor.py:161} INFO - Started process (PID=1060) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:32:43.243+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:32:43.245+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:32:43.245+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:32:43.279+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:32:43.273+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:32:43.282+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:32:43.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.068 seconds
[2024-12-22T18:33:13.835+0000] {processor.py:161} INFO - Started process (PID=1119) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:33:13.836+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:33:13.839+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:33:13.838+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:33:13.875+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:33:13.869+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:33:13.877+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:33:13.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.076 seconds
[2024-12-22T18:33:44.639+0000] {processor.py:161} INFO - Started process (PID=1179) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:33:44.640+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:33:44.642+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:33:44.642+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:33:44.672+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:33:44.667+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:33:44.674+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:33:44.696+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.063 seconds
[2024-12-22T18:34:15.006+0000] {processor.py:161} INFO - Started process (PID=1238) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:34:15.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:34:15.009+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:34:15.009+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:34:15.040+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:34:15.035+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:34:15.042+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:34:15.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.063 seconds
[2024-12-22T18:34:45.558+0000] {processor.py:161} INFO - Started process (PID=1297) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:34:45.560+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:34:45.562+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:34:45.561+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:34:45.591+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:34:45.586+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:34:45.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:34:45.619+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.066 seconds
[2024-12-22T18:35:16.077+0000] {processor.py:161} INFO - Started process (PID=1356) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:35:16.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:35:16.080+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:35:16.080+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:35:16.111+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:35:16.106+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:35:16.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:35:16.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.064 seconds
[2024-12-22T18:35:46.467+0000] {processor.py:161} INFO - Started process (PID=1415) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:35:46.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:35:46.470+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:35:46.470+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:35:46.504+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:35:46.499+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:35:46.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:35:46.529+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.070 seconds
[2024-12-22T18:36:16.793+0000] {processor.py:161} INFO - Started process (PID=1474) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:36:16.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:36:16.796+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:36:16.796+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:36:16.825+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:36:16.821+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:36:16.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:36:16.850+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.062 seconds
[2024-12-22T18:36:47.867+0000] {processor.py:161} INFO - Started process (PID=1533) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:36:47.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:36:47.870+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:36:47.870+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:36:47.901+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:36:47.895+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:36:47.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:36:47.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.065 seconds
[2024-12-22T18:37:18.479+0000] {processor.py:161} INFO - Started process (PID=1593) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:37:18.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:37:18.483+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:37:18.483+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:37:18.515+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:37:18.509+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:37:18.517+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:37:18.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.071 seconds
[2024-12-22T18:37:48.810+0000] {processor.py:161} INFO - Started process (PID=1652) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:37:48.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:37:48.814+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:37:48.813+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:37:48.847+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:37:48.842+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:37:48.848+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:37:48.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.066 seconds
[2024-12-22T18:38:19.798+0000] {processor.py:161} INFO - Started process (PID=1711) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:38:19.799+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:38:19.802+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:38:19.801+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:38:19.833+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:38:19.828+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:38:19.835+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:38:19.857+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.063 seconds
[2024-12-22T18:38:50.111+0000] {processor.py:161} INFO - Started process (PID=1770) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:38:50.112+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:38:50.114+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:38:50.114+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:38:50.144+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:38:50.139+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:38:50.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:38:50.168+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.063 seconds
[2024-12-22T18:39:21.121+0000] {processor.py:161} INFO - Started process (PID=1829) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:39:21.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:39:21.125+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:39:21.124+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:39:21.156+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:39:21.150+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:39:21.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:39:21.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.063 seconds
[2024-12-22T18:39:51.866+0000] {processor.py:161} INFO - Started process (PID=1889) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:39:51.867+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:39:51.869+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:39:51.869+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:39:51.901+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:39:51.897+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:39:51.903+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:39:51.923+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.063 seconds
[2024-12-22T18:40:22.458+0000] {processor.py:161} INFO - Started process (PID=1948) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:40:22.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:40:22.461+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:40:22.461+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:40:22.490+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:40:22.485+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:40:22.492+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:40:22.513+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.060 seconds
[2024-12-22T18:40:53.186+0000] {processor.py:161} INFO - Started process (PID=2007) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:40:53.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:40:53.189+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:40:53.189+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:40:53.219+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:40:53.214+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:40:53.221+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:40:53.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.062 seconds
[2024-12-22T18:41:23.778+0000] {processor.py:161} INFO - Started process (PID=2066) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:41:23.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:41:23.783+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:41:23.783+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:41:23.823+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:41:23.816+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:41:23.826+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:41:23.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.086 seconds
[2024-12-22T18:41:54.314+0000] {processor.py:161} INFO - Started process (PID=2125) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:41:54.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:41:54.318+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:41:54.318+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:41:54.350+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:41:54.346+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:41:54.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:41:54.374+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.065 seconds
[2024-12-22T18:42:24.973+0000] {processor.py:161} INFO - Started process (PID=2184) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:42:24.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:42:24.978+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:42:24.977+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:42:25.024+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:42:25.016+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:42:25.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:42:25.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.092 seconds
[2024-12-22T18:42:55.641+0000] {processor.py:161} INFO - Started process (PID=2249) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:42:55.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:42:55.644+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:42:55.644+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:42:55.674+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:42:55.669+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:42:55.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:42:55.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.063 seconds
[2024-12-22T18:43:26.254+0000] {processor.py:161} INFO - Started process (PID=2308) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:43:26.255+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:43:26.258+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:43:26.258+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:43:26.288+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:43:26.283+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:43:26.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:43:26.313+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.063 seconds
[2024-12-22T18:43:56.776+0000] {processor.py:161} INFO - Started process (PID=2367) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:43:56.777+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:43:56.780+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:43:56.779+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:43:56.811+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:43:56.805+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:43:56.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:43:56.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.067 seconds
[2024-12-22T18:44:27.708+0000] {processor.py:161} INFO - Started process (PID=2426) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:44:27.709+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:44:27.711+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:44:27.711+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:44:27.742+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:44:27.736+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:44:27.744+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:44:27.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.062 seconds
[2024-12-22T18:44:58.403+0000] {processor.py:161} INFO - Started process (PID=2485) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:44:58.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:44:58.407+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:44:58.407+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:44:58.438+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:44:58.433+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:44:58.440+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:44:58.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.065 seconds
[2024-12-22T18:45:28.896+0000] {processor.py:161} INFO - Started process (PID=2544) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:45:28.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:45:28.900+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:45:28.899+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:45:28.932+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:45:28.927+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:45:28.935+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:45:28.958+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.067 seconds
[2024-12-22T18:45:59.340+0000] {processor.py:161} INFO - Started process (PID=2603) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:45:59.341+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:45:59.343+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:45:59.343+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:45:59.374+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:45:59.369+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:45:59.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:45:59.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.067 seconds
[2024-12-22T18:46:30.028+0000] {processor.py:161} INFO - Started process (PID=2662) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:46:30.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:46:30.031+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:46:30.031+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:46:30.062+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:46:30.057+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:46:30.064+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:46:30.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.067 seconds
[2024-12-22T18:47:00.472+0000] {processor.py:161} INFO - Started process (PID=2721) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:47:00.474+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:47:00.477+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:47:00.476+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:47:00.507+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:47:00.501+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:47:00.508+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:47:00.530+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.062 seconds
[2024-12-22T18:47:31.114+0000] {processor.py:161} INFO - Started process (PID=2780) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:47:31.116+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:47:31.118+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:47:31.118+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:47:31.153+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:47:31.147+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:47:31.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:47:31.181+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.073 seconds
[2024-12-22T18:48:01.706+0000] {processor.py:161} INFO - Started process (PID=2839) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:48:01.708+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:48:01.710+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:48:01.709+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:48:01.742+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:48:01.735+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:48:01.744+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:48:01.766+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.064 seconds
[2024-12-22T18:48:32.269+0000] {processor.py:161} INFO - Started process (PID=2898) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:48:32.270+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:48:32.273+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:48:32.272+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:48:32.304+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:48:32.300+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:48:32.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:48:32.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.066 seconds
[2024-12-22T18:49:02.983+0000] {processor.py:161} INFO - Started process (PID=2957) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:49:02.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:49:02.987+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:49:02.986+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:49:03.019+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:49:03.014+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:49:03.022+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:49:03.045+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.067 seconds
[2024-12-22T18:49:34.055+0000] {processor.py:161} INFO - Started process (PID=3016) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:49:34.056+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:49:34.059+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:49:34.058+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:49:34.099+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:49:34.092+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:49:34.102+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:49:34.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.081 seconds
[2024-12-22T18:50:04.204+0000] {processor.py:161} INFO - Started process (PID=3075) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:50:04.205+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:50:04.208+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:50:04.207+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:50:04.249+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:50:04.244+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:50:04.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:50:04.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.082 seconds
[2024-12-22T18:50:35.006+0000] {processor.py:161} INFO - Started process (PID=3134) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:50:35.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:50:35.009+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:50:35.009+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:50:35.046+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:50:35.039+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:50:35.049+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:50:35.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.072 seconds
[2024-12-22T18:51:06.003+0000] {processor.py:161} INFO - Started process (PID=3193) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:51:06.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:51:06.008+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:51:06.007+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:51:06.043+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:51:06.038+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:51:06.045+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:51:06.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.074 seconds
[2024-12-22T18:51:31.352+0000] {processor.py:161} INFO - Started process (PID=3252) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:51:31.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:51:31.356+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:51:31.356+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:51:31.418+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:51:31.410+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:51:31.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:51:31.452+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.107 seconds
[2024-12-22T18:52:01.926+0000] {processor.py:161} INFO - Started process (PID=3311) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:52:01.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:52:01.929+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:52:01.929+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:52:01.961+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:52:01.956+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:52:01.963+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:52:01.986+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.067 seconds
[2024-12-22T18:52:22.650+0000] {processor.py:161} INFO - Started process (PID=3330) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:52:22.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:52:22.654+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:52:22.653+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:52:22.707+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:52:22.701+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'src'
[2024-12-22T18:52:22.709+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:52:22.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.091 seconds
[2024-12-22T18:52:36.351+0000] {processor.py:161} INFO - Started process (PID=3371) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:52:36.353+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:52:36.356+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:52:36.355+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:52:36.416+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:52:36.411+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:52:36.418+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:52:36.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.102 seconds
[2024-12-22T18:53:06.809+0000] {processor.py:161} INFO - Started process (PID=3430) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:53:06.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:53:06.813+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:53:06.812+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:53:06.847+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:53:06.841+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:53:06.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:53:06.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.074 seconds
[2024-12-22T18:53:37.233+0000] {processor.py:161} INFO - Started process (PID=3489) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:53:37.234+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:53:37.236+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:53:37.235+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:53:37.271+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:53:37.265+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 11, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:53:37.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:53:37.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.083 seconds
[2024-12-22T18:54:01.738+0000] {processor.py:161} INFO - Started process (PID=3548) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:54:01.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:54:01.746+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:54:01.745+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:54:01.803+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:54:01.796+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 12, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:54:01.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:54:01.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.109 seconds
[2024-12-22T18:54:16.997+0000] {processor.py:161} INFO - Started process (PID=3549) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:54:16.998+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:54:17.000+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:54:17.000+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:54:17.046+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:54:17.041+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 12, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:54:17.048+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:54:17.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.082 seconds
[2024-12-22T18:54:47.139+0000] {processor.py:161} INFO - Started process (PID=3608) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:54:47.140+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:54:47.143+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:54:47.142+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:54:47.176+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:54:47.170+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 12, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:54:47.178+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:54:47.204+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.073 seconds
[2024-12-22T18:55:17.390+0000] {processor.py:161} INFO - Started process (PID=3667) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:55:17.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:55:17.393+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:55:17.393+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:55:17.422+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:55:17.418+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 12, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:55:17.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:55:17.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.062 seconds
[2024-12-22T18:55:48.013+0000] {processor.py:161} INFO - Started process (PID=3726) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:55:48.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:55:48.017+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:55:48.016+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:55:48.047+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:55:48.042+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 12, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:55:48.049+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:55:48.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.064 seconds
[2024-12-22T18:56:11.967+0000] {processor.py:161} INFO - Started process (PID=3785) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:56:11.968+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:56:11.971+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:56:11.970+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:56:12.015+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:56:12.009+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:56:12.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:56:12.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.078 seconds
[2024-12-22T18:56:31.277+0000] {processor.py:161} INFO - Started process (PID=3826) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:56:31.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:56:31.281+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:56:31.280+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:56:31.312+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:56:31.310+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 14
    sys.path.append(os.path.join(PROJECT_ROOT, "src")
                   ^
SyntaxError: '(' was never closed
[2024-12-22T18:56:31.313+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:56:31.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.079 seconds
[2024-12-22T18:56:33.983+0000] {processor.py:161} INFO - Started process (PID=3834) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:56:33.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:56:33.986+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:56:33.986+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:56:34.035+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:56:34.028+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:56:34.039+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:56:34.068+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.091 seconds
[2024-12-22T18:57:04.177+0000] {processor.py:161} INFO - Started process (PID=3893) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:57:04.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:57:04.181+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:57:04.180+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:57:04.230+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:57:04.224+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T18:57:04.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:57:04.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.083 seconds
[2024-12-22T18:57:17.165+0000] {processor.py:161} INFO - Started process (PID=3905) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:57:17.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:57:17.168+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:57:17.167+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:57:17.226+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:57:17.217+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'src'
[2024-12-22T18:57:17.228+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:57:17.256+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.098 seconds
[2024-12-22T18:57:45.177+0000] {processor.py:161} INFO - Started process (PID=3964) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:57:45.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:57:45.180+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:57:45.180+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:57:45.232+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:57:45.225+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from MyProject.src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'MyProject'
[2024-12-22T18:57:45.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:57:45.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.089 seconds
[2024-12-22T18:58:16.009+0000] {processor.py:161} INFO - Started process (PID=4023) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:58:16.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:58:16.013+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:58:16.013+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:58:16.046+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:58:16.041+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from MyProject.src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'MyProject'
[2024-12-22T18:58:16.049+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:58:16.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.073 seconds
[2024-12-22T18:58:46.296+0000] {processor.py:161} INFO - Started process (PID=4082) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:58:46.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:58:46.300+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:58:46.299+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:58:46.331+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:58:46.326+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from MyProject.src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'MyProject'
[2024-12-22T18:58:46.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:58:46.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.066 seconds
[2024-12-22T18:59:17.237+0000] {processor.py:161} INFO - Started process (PID=4141) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:59:17.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:59:17.240+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:59:17.240+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:59:17.273+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:59:17.267+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from MyProject.src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'MyProject'
[2024-12-22T18:59:17.275+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:59:17.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.068 seconds
[2024-12-22T18:59:47.968+0000] {processor.py:161} INFO - Started process (PID=4200) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:59:47.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T18:59:47.972+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:59:47.971+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:59:48.004+0000] {logging_mixin.py:188} INFO - [2024-12-22T18:59:47.999+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from MyProject.src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'MyProject'
[2024-12-22T18:59:48.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T18:59:48.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.065 seconds
[2024-12-22T19:00:18.240+0000] {processor.py:161} INFO - Started process (PID=4259) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:00:18.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:00:18.244+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:00:18.243+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:00:18.273+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:00:18.268+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from MyProject.src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'MyProject'
[2024-12-22T19:00:18.275+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:00:18.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.062 seconds
[2024-12-22T19:00:48.810+0000] {processor.py:161} INFO - Started process (PID=4318) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:00:48.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:00:48.813+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:00:48.813+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:00:48.847+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:00:48.841+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from MyProject.src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'MyProject'
[2024-12-22T19:00:48.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:00:48.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.068 seconds
[2024-12-22T19:01:04.021+0000] {processor.py:161} INFO - Started process (PID=4352) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:01:04.022+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:01:04.024+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:01:04.024+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:01:04.076+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:01:04.070+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from MyProject.src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'MyProject'
[2024-12-22T19:01:04.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:01:04.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.089 seconds
[2024-12-22T19:01:30.380+0000] {processor.py:161} INFO - Started process (PID=4394) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:01:30.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:01:30.384+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:01:30.384+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:01:30.432+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:01:30.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'src'
[2024-12-22T19:01:30.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:01:30.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.083 seconds
[2024-12-22T19:02:00.910+0000] {processor.py:161} INFO - Started process (PID=4450) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:02:00.911+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:02:00.913+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:02:00.913+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:02:00.946+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:02:00.941+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'src'
[2024-12-22T19:02:00.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:02:00.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.068 seconds
[2024-12-22T19:02:31.506+0000] {processor.py:161} INFO - Started process (PID=4509) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:02:31.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:02:31.510+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:02:31.509+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:02:31.541+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:02:31.535+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'src'
[2024-12-22T19:02:31.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:02:31.567+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.067 seconds
[2024-12-22T19:03:01.929+0000] {processor.py:161} INFO - Started process (PID=4568) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:03:01.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:03:01.934+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:03:01.933+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:03:01.973+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:03:01.966+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'src'
[2024-12-22T19:03:01.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:03:02.006+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.083 seconds
[2024-12-22T19:03:32.366+0000] {processor.py:161} INFO - Started process (PID=4627) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:03:32.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:03:32.370+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:03:32.370+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:03:32.403+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:03:32.398+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'src'
[2024-12-22T19:03:32.406+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:03:32.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.071 seconds
[2024-12-22T19:04:02.599+0000] {processor.py:161} INFO - Started process (PID=4687) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:04:02.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:04:02.602+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:04:02.601+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:04:02.634+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:04:02.629+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'src'
[2024-12-22T19:04:02.636+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:04:02.658+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.064 seconds
[2024-12-22T19:04:33.370+0000] {processor.py:161} INFO - Started process (PID=4746) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:04:33.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:04:33.374+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:04:33.373+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:04:33.404+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:04:33.399+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'src'
[2024-12-22T19:04:33.406+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:04:33.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.065 seconds
[2024-12-22T19:05:03.811+0000] {processor.py:161} INFO - Started process (PID=4805) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:05:03.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:05:03.815+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:05:03.814+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:05:03.846+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:05:03.840+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'src'
[2024-12-22T19:05:03.849+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:05:03.870+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.065 seconds
[2024-12-22T19:05:34.023+0000] {processor.py:161} INFO - Started process (PID=4864) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:05:34.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:05:34.026+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:05:34.025+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:05:34.058+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:05:34.052+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'src'
[2024-12-22T19:05:34.061+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:05:34.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.069 seconds
[2024-12-22T19:06:04.288+0000] {processor.py:161} INFO - Started process (PID=4923) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:06:04.289+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:06:04.292+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:06:04.291+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:06:04.336+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:06:04.329+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'src'
[2024-12-22T19:06:04.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:06:04.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.090 seconds
[2024-12-22T19:06:34.483+0000] {processor.py:161} INFO - Started process (PID=4982) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:06:34.484+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:06:34.487+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:06:34.486+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:06:34.516+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:06:34.512+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'src'
[2024-12-22T19:06:34.519+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:06:34.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.063 seconds
[2024-12-22T19:07:04.788+0000] {processor.py:161} INFO - Started process (PID=5041) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:07:04.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:07:04.791+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:07:04.790+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:07:04.835+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:07:04.828+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from src.stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'src'
[2024-12-22T19:07:04.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:07:04.867+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.084 seconds
[2024-12-22T19:07:07.194+0000] {processor.py:161} INFO - Started process (PID=5059) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:07:07.195+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:07:07.198+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:07:07.198+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:07:07.246+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:07:07.240+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from plugins.insert_data_to_db import (
ModuleNotFoundError: No module named 'plugins'
[2024-12-22T19:07:07.248+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:07:07.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.085 seconds
[2024-12-22T19:07:28.439+0000] {processor.py:161} INFO - Started process (PID=5095) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:07:28.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:07:28.442+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:07:28.442+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:07:28.488+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:07:28.482+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from plugins.insert_data_to_db import (
ModuleNotFoundError: No module named 'plugins'
[2024-12-22T19:07:28.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:07:28.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.082 seconds
[2024-12-22T19:07:31.478+0000] {processor.py:161} INFO - Started process (PID=5096) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:07:31.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:07:31.481+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:07:31.481+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:07:31.526+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:07:31.521+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from plugins.insert_data_to_db import (
ModuleNotFoundError: No module named 'plugins'
[2024-12-22T19:07:31.528+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:07:31.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.079 seconds
[2024-12-22T19:08:01.736+0000] {processor.py:161} INFO - Started process (PID=5155) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:08:01.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:08:01.739+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:08:01.739+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:08:01.771+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:08:01.766+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from plugins.insert_data_to_db import (
ModuleNotFoundError: No module named 'plugins'
[2024-12-22T19:08:01.774+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:08:01.799+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.068 seconds
[2024-12-22T19:08:32.397+0000] {processor.py:161} INFO - Started process (PID=5214) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:08:32.399+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:08:32.404+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:08:32.403+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:08:32.460+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:08:32.450+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from plugins.insert_data_to_db import (
ModuleNotFoundError: No module named 'plugins'
[2024-12-22T19:08:32.463+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:08:32.507+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.121 seconds
[2024-12-22T19:09:00.860+0000] {processor.py:161} INFO - Started process (PID=5273) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:09:00.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:09:00.864+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:09:00.863+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:09:00.910+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:09:00.905+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 4, in <module>
    from utils.helpers import load_cfg
ModuleNotFoundError: No module named 'utils'
[2024-12-22T19:09:00.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:09:00.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.082 seconds
[2024-12-22T19:09:26.506+0000] {processor.py:161} INFO - Started process (PID=5326) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:09:26.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:09:26.509+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:09:26.509+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:09:26.552+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:09:26.546+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 4, in <module>
    from utils.helpers import load_cfg
ModuleNotFoundError: No module named 'utils'
[2024-12-22T19:09:26.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:09:26.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.077 seconds
[2024-12-22T19:09:56.738+0000] {processor.py:161} INFO - Started process (PID=5385) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:09:56.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:09:56.742+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:09:56.742+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:09:56.773+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:09:56.767+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 4, in <module>
    from utils.helpers import load_cfg
ModuleNotFoundError: No module named 'utils'
[2024-12-22T19:09:56.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:09:56.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.079 seconds
[2024-12-22T19:10:26.936+0000] {processor.py:161} INFO - Started process (PID=5444) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:10:26.937+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:10:26.940+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:10:26.940+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:10:26.975+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:10:26.968+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 4, in <module>
    from utils.helpers import load_cfg
ModuleNotFoundError: No module named 'utils'
[2024-12-22T19:10:26.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:10:27.002+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.071 seconds
[2024-12-22T19:10:57.071+0000] {processor.py:161} INFO - Started process (PID=5503) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:10:57.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:10:57.074+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:10:57.074+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:10:57.107+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:10:57.102+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 4, in <module>
    from utils.helpers import load_cfg
ModuleNotFoundError: No module named 'utils'
[2024-12-22T19:10:57.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:10:57.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.069 seconds
[2024-12-22T19:11:27.446+0000] {processor.py:161} INFO - Started process (PID=5562) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:11:27.447+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:11:27.449+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:11:27.449+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:11:27.479+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:11:27.473+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 4, in <module>
    from utils.helpers import load_cfg
ModuleNotFoundError: No module named 'utils'
[2024-12-22T19:11:27.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:11:27.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.065 seconds
[2024-12-22T19:11:58.293+0000] {processor.py:161} INFO - Started process (PID=5625) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:11:58.294+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:11:58.296+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:11:58.296+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:11:58.327+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:11:58.322+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 4, in <module>
    from utils.helpers import load_cfg
ModuleNotFoundError: No module named 'utils'
[2024-12-22T19:11:58.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:11:58.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.064 seconds
[2024-12-22T19:12:28.925+0000] {processor.py:161} INFO - Started process (PID=5684) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:12:28.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:12:28.929+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:12:28.928+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:12:28.960+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:12:28.955+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 4, in <module>
    from utils.helpers import load_cfg
ModuleNotFoundError: No module named 'utils'
[2024-12-22T19:12:28.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:12:28.986+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.066 seconds
[2024-12-22T19:12:59.040+0000] {processor.py:161} INFO - Started process (PID=5743) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:12:59.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:12:59.044+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:12:59.043+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:12:59.075+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:12:59.070+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 4, in <module>
    from utils.helpers import load_cfg
ModuleNotFoundError: No module named 'utils'
[2024-12-22T19:12:59.077+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:12:59.100+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.065 seconds
[2024-12-22T19:13:29.244+0000] {processor.py:161} INFO - Started process (PID=5802) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:13:29.246+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:13:29.248+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:13:29.248+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:13:29.280+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:13:29.274+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 4, in <module>
    from utils.helpers import load_cfg
ModuleNotFoundError: No module named 'utils'
[2024-12-22T19:13:29.282+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:13:29.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.066 seconds
[2024-12-22T19:13:33.842+0000] {processor.py:161} INFO - Started process (PID=5805) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:13:33.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:13:33.846+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:13:33.845+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:13:33.888+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:13:33.883+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 4, in <module>
    from utils.helpers import load_cfg
ModuleNotFoundError: No module named 'utils'
[2024-12-22T19:13:33.890+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:13:33.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.076 seconds
[2024-12-22T19:13:45.004+0000] {processor.py:161} INFO - Started process (PID=5836) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:13:45.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:13:45.007+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:13:45.007+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:13:45.051+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:13:45.045+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 4, in <module>
    from utils.helpers import load_cfg
ModuleNotFoundError: No module named 'utils'
[2024-12-22T19:13:45.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:13:45.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.078 seconds
[2024-12-22T19:13:50.716+0000] {processor.py:161} INFO - Started process (PID=5847) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:13:50.717+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:13:50.720+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:13:50.719+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:13:50.773+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:13:50.767+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T19:13:50.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:13:50.799+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.088 seconds
[2024-12-22T19:14:20.980+0000] {processor.py:161} INFO - Started process (PID=5906) to work on /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:14:20.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pipline_stream.py for tasks to queue
[2024-12-22T19:14:20.984+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:14:20.984+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:14:21.023+0000] {logging_mixin.py:188} INFO - [2024-12-22T19:14:21.016+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/pipline_stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipline_stream.py", line 16, in <module>
    from stream_processing.insert_data_to_db import (
ModuleNotFoundError: No module named 'stream_processing'
[2024-12-22T19:14:21.026+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pipline_stream.py
[2024-12-22T19:14:21.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pipline_stream.py took 0.075 seconds
