[2024-12-23T11:04:37.191+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-23T11:04:37.231+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: streaming_pipeline.image_to_datalake manual__2024-12-23T11:04:33.292563+00:00 [queued]>
[2024-12-23T11:04:37.243+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: streaming_pipeline.image_to_datalake manual__2024-12-23T11:04:33.292563+00:00 [queued]>
[2024-12-23T11:04:37.244+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-23T11:04:37.262+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): image_to_datalake> on 2024-12-23 11:04:33.292563+00:00
[2024-12-23T11:04:37.272+0000] {standard_task_runner.py:63} INFO - Started process 3821 to run task
[2024-12-23T11:04:37.275+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'streaming_pipeline', 'image_to_datalake', 'manual__2024-12-23T11:04:33.292563+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/pipline_stream.py', '--cfg-path', '/tmp/tmpuql3dq4s']
[2024-12-23T11:04:37.278+0000] {standard_task_runner.py:91} INFO - Job 107: Subtask image_to_datalake
[2024-12-23T11:04:37.342+0000] {task_command.py:426} INFO - Running <TaskInstance: streaming_pipeline.image_to_datalake manual__2024-12-23T11:04:33.292563+00:00 [running]> on host 0b4a5bf62610
[2024-12-23T11:04:37.450+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='streaming_pipeline' AIRFLOW_CTX_TASK_ID='image_to_datalake' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T11:04:33.292563+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T11:04:33.292563+00:00'
[2024-12-23T11:04:37.452+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-23T11:04:37.482+0000] {logging_mixin.py:188} INFO - Bucket raw already exists, skip creating!
[2024-12-23T11:04:37.486+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.9', 29092)]>: connecting to broker:29092 [('172.19.0.9', 29092) IPv4]
[2024-12-23T11:04:37.488+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-12-23T11:04:37.490+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.9', 29092)]>: Connection complete.
[2024-12-23T11:04:37.601+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-12-23T11:04:37.602+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-12-23T11:04:37.605+0000] {consumer.py:122} WARNING - group_id is None: disabling auto-commit.
[2024-12-23T11:04:37.606+0000] {subscription_state.py:167} INFO - Updating subscribed topics to: ('raw_image_2024_2',)
[2024-12-23T11:04:37.607+0000] {logging_mixin.py:188} INFO - Start consuming messages...
[2024-12-23T11:04:37.609+0000] {subscription_state.py:253} INFO - Updated partition assignment: [('raw_image_2024_2', 0)]
[2024-12-23T11:04:37.611+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.19.0.9', 29092)]>: connecting to broker:29092 [('172.19.0.9', 29092) IPv4]
[2024-12-23T11:04:37.615+0000] {conn.py:393} INFO - <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.19.0.9', 29092)]>: Connection complete.
[2024-12-23T11:04:37.616+0000] {conn.py:673} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.19.0.9', 29092)]>: Closing connection. 
[2024-12-23T11:04:38.281+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000001.jpg
[2024-12-23T11:04:40.700+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000002.jpg
[2024-12-23T11:04:43.023+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000003.jpg
[2024-12-23T11:04:45.426+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000004.jpg
[2024-12-23T11:04:47.728+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000005.jpg
[2024-12-23T11:04:50.028+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000006.jpg
[2024-12-23T11:04:52.335+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000007.jpg
[2024-12-23T11:04:54.628+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000008.jpg
[2024-12-23T11:04:56.941+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000009.jpg
[2024-12-23T11:04:59.273+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000010.jpg
[2024-12-23T11:05:01.599+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000011.jpg
[2024-12-23T11:05:03.946+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000012.jpg
[2024-12-23T11:05:06.280+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000013.jpg
[2024-12-23T11:05:08.912+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000014.jpg
[2024-12-23T11:05:11.328+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000015.jpg
[2024-12-23T11:05:13.615+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000016.jpg
[2024-12-23T11:05:15.953+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000017.jpg
[2024-12-23T11:05:18.503+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000018.jpg
[2024-12-23T11:05:20.993+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000019.jpg
[2024-12-23T11:05:23.466+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000020.jpg
[2024-12-23T11:05:25.915+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000021.jpg
[2024-12-23T11:05:28.251+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000022.jpg
[2024-12-23T11:05:30.593+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000023.jpg
[2024-12-23T11:05:32.913+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000024.jpg
[2024-12-23T11:05:35.314+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000025.jpg
[2024-12-23T11:05:37.822+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000026.jpg
[2024-12-23T11:05:40.317+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000027.jpg
[2024-12-23T11:05:42.723+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000028.jpg
[2024-12-23T11:05:45.053+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000029.jpg
[2024-12-23T11:05:47.460+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000030.jpg
[2024-12-23T11:05:49.788+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000031.jpg
[2024-12-23T11:05:52.075+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000032.jpg
[2024-12-23T11:05:54.399+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000033.jpg
[2024-12-23T11:05:56.669+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000034.jpg
[2024-12-23T11:05:58.937+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000035.jpg
[2024-12-23T11:06:01.226+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000036.jpg
[2024-12-23T11:06:03.518+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000037.jpg
[2024-12-23T11:06:05.888+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000038.jpg
[2024-12-23T11:06:08.207+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000039.jpg
[2024-12-23T11:06:10.619+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000040.jpg
[2024-12-23T11:06:12.924+0000] {logging_mixin.py:188} INFO - File đã được lưu thành công vào MinIO: image/2024/2/20240200000041.jpg
[2024-12-23T11:06:55.354+0000] {fetcher.py:847} INFO - Fetch offset 41 is out of range for topic-partition ('raw_image_2024_2', 0)
[2024-12-23T11:07:44.334+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-12-23T11:07:44.335+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-12-23T11:07:44.339+0000] {process_utils.py:132} INFO - Sending 15 to group 3821. PIDs of all processes in the group: [3821]
[2024-12-23T11:07:44.340+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 3821
[2024-12-23T11:07:44.341+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-23T11:07:44.342+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-23T11:07:44.353+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stream_processing/streaming_image_to_dl.py", line 59, in image_to_dl
    for message in consumer:
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/consumer/group.py", line 1203, in __next__
    return self.next_v2()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/consumer/group.py", line 1211, in next_v2
    return next(self._iterator)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/consumer/group.py", line 1126, in _message_generator_v2
    record_map = self.poll(timeout_ms=timeout_ms, update_offsets=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/consumer/group.py", line 663, in poll
    records = self._poll_once(remaining, max_records, update_offsets=update_offsets)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/consumer/group.py", line 712, in _poll_once
    self._client.poll(timeout_ms=timeout_ms)
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 601, in poll
    self._poll(timeout / 1000)
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 633, in _poll
    ready = self._selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-23T11:07:44.369+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=streaming_pipeline, task_id=image_to_datalake, run_id=manual__2024-12-23T11:04:33.292563+00:00, execution_date=20241223T110433, start_date=20241223T110437, end_date=20241223T110744
[2024-12-23T11:07:44.385+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 107 for task image_to_datalake ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(streaming_pipeline, image_to_datalake, manual__2024-12-23T11:04:33.292563+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'image_to_datalake', 'dag_id': 'streaming_pipeline', 'run_id': 'manual__2024-12-23T11:04:33.292563+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 12, 23, 11, 4, 37, 232587, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 12, 23, 11, 7, 44, 368875, tzinfo=Timezone('UTC')), 'duration': 187}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 3821)
[2024-12-23T11:07:44.433+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3821, status='terminated', exitcode=1, started='11:04:37') (3821) terminated with exit code 1
